"""add_indexes_and_constraints_to_feature_flags

Revision ID: 434adb8fc9eb
Revises: 44f103ebfb95
Create Date: 2026-07-29 23:53:06.694621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434adb8fc9eb'
down_revision: Union[str, Sequence[str], None] = '44f103ebfb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feature_flags_environment_id'), 'feature_flags', ['environment_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    op.create_unique_constraint('uq_environment_flag_key', 'feature_flags', ['environment_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_environment_flag_key', 'feature_flags', type_='unique')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_environment_id'), table_name='feature_flags')
    # ### end Alembic commands ###
