"""add environment_id and default_value to feature_flags

Revision ID: 44f103ebfb95
Revises: 71f3aae0e552
Create Date: 2026-07-27 23:58:55.223463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f103ebfb95'
down_revision: Union[str, Sequence[str], None] = '71f3aae0e552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.add_column('feature_flags', sa.Column('default_value', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'feature_flags', 'environments', ['environment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature_flags', type_='foreignkey')
    op.drop_column('feature_flags', 'default_value')
    op.drop_column('feature_flags', 'environment_id')
    # ### end Alembic commands ###
